Resources:
  CategoriesTable9FFF5A67:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/CategoriesTable/Resource
  FeaturedTableBAADB5A4:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/FeaturedTable/Resource
  snackerlambdaServiceRole680C9A87:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-lambda/ServiceRole/Resource
  snackerlambdaServiceRoleDefaultPolicy0B57C77E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - dynamodb:BatchGetItem
          - dynamodb:ConditionCheckItem
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:Query
          - dynamodb:Scan
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - CategoriesTable9FFF5A67
            - Arn
          - Fn::GetAtt:
            - FeaturedTableBAADB5A4
            - Arn
          - Ref: AWS::NoValue
        Version: '2012-10-17'
      PolicyName: snackerlambdaServiceRoleDefaultPolicy0B57C77E
      Roles:
      - Ref: snackerlambdaServiceRole680C9A87
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-lambda/ServiceRole/DefaultPolicy/Resource
  snackerlambda88F4AB10:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 6b029e2562d356ad17dc1e2ba878c5d7aa278308554e2e862f7eb17ce419de63.zip
      Environment:
        Variables:
          CATEGORIES_TABLE_NAME:
            Ref: CategoriesTable9FFF5A67
          FEATURED_TABLE_NAME:
            Ref: FeaturedTableBAADB5A4
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - snackerlambdaServiceRole680C9A87
        - Arn
      Runtime: nodejs14.x
    DependsOn:
    - snackerlambdaServiceRoleDefaultPolicy0B57C77E
    - snackerlambdaServiceRole680C9A87
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-lambda/Resource
      aws:asset:path: asset.6b029e2562d356ad17dc1e2ba878c5d7aa278308554e2e862f7eb17ce419de63
      aws:asset:is-bundled: false
      aws:asset:property: Code
  snackerapi40080B67:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: snacker-api
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Resource
  snackerapiDeploymentC4518BA29746baf4be5ee5da25d37835319fa594:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: snackerapi40080B67
    DependsOn:
    - snackerapicategoriesGETC765426F
    - snackerapicategories685EE0D1
    - snackerapifeaturedGETCA88EB1E
    - snackerapifeaturedAC1517CB
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Deployment/Resource
  snackerapiDeploymentStageprodA7633B37:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: snackerapiDeploymentC4518BA29746baf4be5ee5da25d37835319fa594
      RestApiId:
        Ref: snackerapi40080B67
      StageName: prod
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/DeploymentStage.prod/Resource
  snackerapicategories685EE0D1:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
        - snackerapi40080B67
        - RootResourceId
      PathPart: categories
      RestApiId:
        Ref: snackerapi40080B67
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/categories/Resource
  snackerapicategoriesGETApiPermissionSnackerAwsBackendStacksnackerapi6EBCEBCDGETcategories02B6EB10:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - snackerlambda88F4AB10
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":execute-api:"
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: snackerapi40080B67
          - "/"
          - Ref: snackerapiDeploymentStageprodA7633B37
          - "/GET/categories"
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/categories/GET/ApiPermission.SnackerAwsBackendStacksnackerapi6EBCEBCD.GET..categories
  snackerapicategoriesGETApiPermissionTestSnackerAwsBackendStacksnackerapi6EBCEBCDGETcategoriesE47F8304:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - snackerlambda88F4AB10
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":execute-api:"
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: snackerapi40080B67
          - "/test-invoke-stage/GET/categories"
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/categories/GET/ApiPermission.Test.SnackerAwsBackendStacksnackerapi6EBCEBCD.GET..categories
  snackerapicategoriesGETC765426F:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
          - ''
          - - 'arn:'
            - Ref: AWS::Partition
            - ":apigateway:"
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - snackerlambda88F4AB10
              - Arn
            - "/invocations"
      ResourceId:
        Ref: snackerapicategories685EE0D1
      RestApiId:
        Ref: snackerapi40080B67
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/categories/GET/Resource
  snackerapifeaturedAC1517CB:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
        - snackerapi40080B67
        - RootResourceId
      PathPart: featured
      RestApiId:
        Ref: snackerapi40080B67
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/featured/Resource
  snackerapifeaturedGETApiPermissionSnackerAwsBackendStacksnackerapi6EBCEBCDGETfeatured224D5B9C:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - snackerlambda88F4AB10
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":execute-api:"
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: snackerapi40080B67
          - "/"
          - Ref: snackerapiDeploymentStageprodA7633B37
          - "/GET/featured"
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/featured/GET/ApiPermission.SnackerAwsBackendStacksnackerapi6EBCEBCD.GET..featured
  snackerapifeaturedGETApiPermissionTestSnackerAwsBackendStacksnackerapi6EBCEBCDGETfeaturedF69ED117:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - snackerlambda88F4AB10
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":execute-api:"
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: snackerapi40080B67
          - "/test-invoke-stage/GET/featured"
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/featured/GET/ApiPermission.Test.SnackerAwsBackendStacksnackerapi6EBCEBCD.GET..featured
  snackerapifeaturedGETCA88EB1E:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
          - ''
          - - 'arn:'
            - Ref: AWS::Partition
            - ":apigateway:"
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - snackerlambda88F4AB10
              - Arn
            - "/invocations"
      ResourceId:
        Ref: snackerapifeaturedAC1517CB
      RestApiId:
        Ref: snackerapi40080B67
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/snacker-api/Default/featured/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WQQU/DMAyFfwv3NDB2GcdtiBtiGtwnNzHFa5NUtcNUVf3vJOkQ4+TPL88vcR715kk/3MGFK2PbqqNaT+8CplVJOk129OCCTeIH1B2q/acvMKsOXG1BTy/RG6Hg89EtH3BwxJy6WRE4PR3DMl/qIXRkxuIrNCten4AZhfU2l9TrXTQtyg4YFfTUgOAFxhSELNueStYVn7HvwujQS1ZvurRKU25dIPlDHAyWzN/mGrTwK8pXsFlaaJ7/fOVhOYh8kx1vUfoo/8YT74O3JGVvHyzqM99/rzZ6tU7ffGaiaoheyKE+LvUHOeHYjYIBAAA=
    Metadata:
      aws:cdk:path: SnackerAwsBackendStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  snackerapiEndpoint693CAB17:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: snackerapi40080B67
        - ".execute-api."
        - Ref: AWS::Region
        - "."
        - Ref: AWS::URLSuffix
        - "/"
        - Ref: snackerapiDeploymentStageprodA7633B37
        - "/"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - af-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ca-central-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-northwest-1
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-central-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-2
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-3
      - Fn::Equals:
        - Ref: AWS::Region
        - me-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - sa-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-2
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/cdk-bootstrap/hnb659fds/version"
    Description: Version of the CDK Bootstrap resources in this environment, automatically
      retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
    - Assert:
        Fn::Not:
        - Fn::Contains:
          - - '1'
            - '2'
            - '3'
            - '4'
            - '5'
          - Ref: BootstrapVersion
      AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap'
        with a recent version of the CDK CLI.
